# Generated by Django 3.1.7 on 2021-06-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Enrolment',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('slug', models.SlugField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=None, null=True)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('students', models.ManyToManyField(related_name='subjects', through='main.Enrol', to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('title', models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Prof', 'Prof')], max_length=10, null=True)),
                ('bio', models.TextField(default=None, null=True)),
                ('subject', models.ManyToManyField(to='main.Subject')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.account',),
        ),
        migrations.AddField(
            model_name='enrol',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AddField(
            model_name='enrol',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
    ]
