# Generated by Django 3.1.7 on 2021-06-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.IntegerField(choices=[(1, '10'), (2, '11'), (3, '12')], default=None, null=True),
        ),
    ]
