# Generated by Django 3.1.7 on 2021-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210620_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.IntegerField(choices=[('10', '10'), ('11', '11'), ('12', '12')], default=None, null=True),
        ),
    ]
