# Generated by Django 3.1.7 on 2021-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210620_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12')], default=None, max_length=10, null=True),
        ),
    ]
