# Generated by Django 3.1.7 on 2021-06-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cover',
        ),
    ]
